-- MySql workbench password: Charged123
CREATE DATABASE MWF11_1;
USE MWF11_1;

CREATE TABLE STUDENTS(
ID INT PRIMARY KEY,
SNAME VARCHAR(50) not null,
AGE INT NOT NULL CHECK (AGE>=18),
CITY VARCHAR(40) NOT NULL DEFAULT "KARACHI",
EMAIL VARCHAR(50) NOT NULL UNIQUE,
GENDER VARCHAR(25) NOT NULL);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS VALUES(1,"ABDULLAH AHSAN",25,"KKER","abc@gmail.com","male"),
(2,"ASHER",18,"KHI","ab1c@gmail.com","male");

INSERT INTO STUDENTS (ID,SNAME,AGE,EMAIL,GENDER) VALUES(3,"HASAN",19,"hasan@gmail.com","male");

INSERT INTO STUDENTS VALUES(4,"HSAN",26,"LAHORE","ahsan@gmail.com","male");
INSERT INTO STUDENTS VALUES(5,"SAN",19,"LAHORE","aan@gmail.com","male");
-- INSERT INTO STUDENTS VALUES(6,"ABDULLAH AHSAN",4,"SUKKER","abcdef@il.com","male");

DROP TABLE STUDENTS;

ALTER TABLE STUDENTS ADD COUNTRY VARCHAR(50) NOT NULL;
ALTER TABLE STUDENTS DROP COUNTRY;
ALTER TABLE STUDENTS MODIFY SNAME VARCHAR(100) NOT NULL;
ALTER TABLE STUDENTS CHANGE SNAME STUDENT_NAME VARCHAR(100) NOT NULL;

SELECT * FROM STUDENTS;
SELECT STUDENT_NAME,CITY FROM STUDENTS;
SELECT EMAIL FROM STUDENTS;

INSERT INTO STUDENTS(ID,SNAME,AGE,EMAIL,GENDER,CITY)
 VALUES(6,"SAMAD",20,"samad@gmail.com","male","LAHORE"),
(7,"M.Anas",21,"anas@gmail.com","male","HYDERABAD"),
(8,"M. HASSAN",22,"HASSAN@GMAIL.COM","MALE","ISLAMABAD");

SELECT *FROM STUDENTS
WHERE AGE >= 20 OR CITY = 'HYDERABAD';

SELECT * FROM STUDENTS
WHERE AGE>19 AND CITY="LAHORE";

SELECT * FROM STUDENTS
WHERE NOT AGE>19 AND NOT CITY="LAHORE";

SELECT * FROM STUDENTS
WHERE NOT  CITY IN ("LAHORE","KHI", "KARACHI");


 update STUDENTS 
 set city= "Sukker"
 where ID =1;
 
SELECT * FROM STUDENTS
WHERE AGE BETWEEN 20 AND 25
LIMIT 3;

SELECT * FROM STUDENTS
WHERE AGE BETWEEN 20 AND 25
ORDER BY SNAME ASC;

SELECT * FROM STUDENTS
WHERE AGE BETWEEN 20 AND 25
ORDER BY AGE DESC;

SELECT MIN(AGE) FROM STUDENTS
WHERE AGE BETWEEN 14 AND 25
ORDER BY AGE DESC;

SELECT AVG(AGE) FROM STUDENTS;
SELECT SUM(AGE) FROM STUDENTS;
SELECT CONCAT(SNAME," FROM ",CITY) FROM STUDENTS;


CREATE DATABASE Products;
USE Products;
CREATE TABLE PAYMENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
PNAME VARCHAR(50) NOT NULL,
p_DATE DATE NOT NULL,
METHOD VARCHAR(50),
CITY VARCHAR(50) NOT NULL
);
SELECT * FROM  PAYMENT;
ALTER TABLE PAYMENT ADD AMOUNT INT NOT NULL;
INSERT INTO PAYMENT (PNAME,p_DATE, METHOD,CITY,AMOUNT) VALUES
("ADNAN","2023-09-29","CASH","KARACHI",45000),
("BILAL","2023-09-29","CARD","LAHORE",30000),
("ZEESHAN","2023-09-30","JAZZCASH","ISLAMABAD",25000),
("SHARIQ","2023-09-28","PAYPAL", "LAHORE",15000),
("ABEEHA","2023-09-29","CASH","KARACHI",28000);

SELECT sum(AMOUNT) FROM PAYMENT
WHERE p_DATE="2023-09-29"
ORDER BY p_DATE ASC;

SELECT p_DATE, sum(AMOUNT), COUNT(ID)  FROM PAYMENT 
GROUP BY p_DATE;

SELECT CITY, sum(AMOUNT), COUNT(ID)  FROM PAYMENT 
GROUP BY CITY ;

SELECT CITY, sum(AMOUNT), COUNT(ID)  FROM PAYMENT 
GROUP BY CITY with rollup;

SELECT METHOD, sum(AMOUNT), COUNT(ID),CITY  FROM PAYMENT 
GROUP BY METHOD
HAVING  CITY="KARACHI" AND NOT METHOD="PAYPAL";

select * from payment;
update payment 
set p_DATE ='2023-09-29'
WHERE ID=3;

update payment 
set METHOD ='CARD'
WHERE METHOD='CASH';

update payment 
set CITY ='KHAIRPUR'
WHERE CITY IN ("LAHORE","ISLAMABAD");

update payment 
set CITY ='KHAIRPUR'
WHERE NOT CITY ="KARACHI";

DELETE FROM PAYMENT 
WHERE AMOUNT BETWEEN 20000 AND 30000;

-- SUB QUERIES
SELECT AVG(AMOUNT) FROM PAYMENT;

SELECT *,(SELECT AVG(AMOUNT) FROM PAYMENT) AS AVERAGE_AMOUNT FROM PAYMENT WHERE
AMOUNT <= (SELECT AVG(AMOUNT) FROM PAYMENT);

SELECT * FROM STUDENTS
WHERE ID IN (SELECT ID FROM STUDENTS
WHERE  ID%2 = 0);



